id: PD434A081
initial_creation_type: ocr
source_metadata:
  volumes:
    99dd38c3ef1e4551ad5944ce8bb47f50:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ལས་ཀྱི་རྡོ་རྗེ་གཽ་རཱིའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
