id: D766B0440
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:07:36+00:00'
last_modified: '2022-05-26T10:46:23.954164+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c3e8:
      image_group_id: I1PD95869
      title: ལས་ཀྱི་རྡོ་རྗེ་གཽ་རཱིའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      order: 24
      base_file: c3e8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
